// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJfi54wsvaIZlIwTwf9LcLzwH2c1XaZk',
    appId: '1:104076391535:web:18e2fa42db7881c603c99a',
    messagingSenderId: '104076391535',
    projectId: 'notes-app-rizqi-25',
    authDomain: 'notes-app-rizqi-25.firebaseapp.com',
    storageBucket: 'notes-app-rizqi-25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFddmDS08azS_Bii7aEq0MZbwnCwa9ccE',
    appId: '1:104076391535:android:8e72b276ebb5fa5103c99a',
    messagingSenderId: '104076391535',
    projectId: 'notes-app-rizqi-25',
    storageBucket: 'notes-app-rizqi-25.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkJfi54wsvaIZlIwTwf9LcLzwH2c1XaZk',
    appId: '1:104076391535:web:d11ebec331af93fc03c99a',
    messagingSenderId: '104076391535',
    projectId: 'notes-app-rizqi-25',
    authDomain: 'notes-app-rizqi-25.firebaseapp.com',
    storageBucket: 'notes-app-rizqi-25.firebasestorage.app',
  );
}
