// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJxBJtS55vSSyaxyjUHKfC9FZEmc5jqk',
    appId: '1:290023216586:web:504eee33f7eb5aebad6b33',
    messagingSenderId: '290023216586',
    projectId: 'fasum-app-4b731',
    authDomain: 'fasum-app-4b731.firebaseapp.com',
    storageBucket: 'fasum-app-4b731.firebasestorage.app',
    measurementId: 'G-NYSLLQ0J3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGk4UvI85pg1kI_IESQmF2da3Sd6FmWDo',
    appId: '1:290023216586:android:d3d7c57130954c0dad6b33',
    messagingSenderId: '290023216586',
    projectId: 'fasum-app-4b731',
    storageBucket: 'fasum-app-4b731.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJxBJtS55vSSyaxyjUHKfC9FZEmc5jqk',
    appId: '1:290023216586:web:d567dbeca5466970ad6b33',
    messagingSenderId: '290023216586',
    projectId: 'fasum-app-4b731',
    authDomain: 'fasum-app-4b731.firebaseapp.com',
    storageBucket: 'fasum-app-4b731.firebasestorage.app',
    measurementId: 'G-GLSQ3PH3V6',
  );
}
