// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABVMqCkAoryjaYWpQjhrzyf6UF_tqPtrk',
    appId: '1:1076757814194:web:3964b4077df2bb83a222ab',
    messagingSenderId: '1076757814194',
    projectId: 'khalbhi-dev',
    authDomain: 'khalbhi-dev.firebaseapp.com',
    databaseURL: 'https://khalbhi-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khalbhi-dev.firebasestorage.app',
    measurementId: 'G-W8Y1M17NP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALbdcTXO-4e8N4-O22YVDypBGFyNycbO4',
    appId: '1:1076757814194:android:66d014bde82482e0a222ab',
    messagingSenderId: '1076757814194',
    projectId: 'khalbhi-dev',
    databaseURL: 'https://khalbhi-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khalbhi-dev.firebasestorage.app',
  );
}